# Generated by Django 3.2.9 on 2021-11-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='surname',
            field=models.CharField(default='surname', max_length=256),
        ),
        migrations.AlterField(
            model_name='manager',
            name='name',
            field=models.CharField(default='name', max_length=256),
        ),
    ]
