# Generated by Django 3.2.9 on 2021-11-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='token',
            field=models.CharField(default='', max_length=256),
        ),
    ]
