# Generated by Django 3.2.9 on 2021-11-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_manager_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='manager',
        ),
    ]
