# Generated by Django 3.2.9 on 2021-11-03 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_meeting_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.manager'),
        ),
    ]
