# Generated by Django 3.2.9 on 2021-11-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211103_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='address',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='meeting',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='meeting',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
