# Generated by Django 3.2.9 on 2021-11-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211104_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='phone',
            field=models.CharField(default='88005553535', max_length=32),
        ),
    ]
