# Generated by Django 3.2.9 on 2021-11-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211105_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
