# Generated by Django 3.2.9 on 2021-11-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_manager_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='manager',
            name='meeting_count',
            field=models.IntegerField(default=0),
        ),
    ]
